export const demoPosts = [
  {
    id: 1,
    title: "The Wonders of Modern Medicine",
    content:
      "In recent years, medical science has made tremendous strides in understanding and treating various diseases,In recent years, medical science has made tremendous strides in understanding and treating various diseases...",
    author: "Dr. Jane Smith",
    diseases: "Various",
    comments: 2,
    createdAt: new Date().toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 2,
    title: "Breakthrough in Cancer Research",
    content:
      "Scientists have discovered a new approach to targeting cancer cells that could revolutionize treatment",
    author: "Prof. Michael Johnson",
    diseases: "Cancer",
    comments: 5,
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 3,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 4,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 5,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 6,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 7,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 8,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 9,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 10,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 11,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
  {
    id: 12,
    title: "The Role of AI in Healthcare",
    content:
      "Artificial Intelligence is playing an increasingly important role in diagnosing diseases and developing treatments",
    author: "Dr. Emily Chen",
    diseases: "Technology",
    comments: 3,
    createdAt: new Date(Date.now() - 172800000).toISOString(),
    color: "from-red-400 to-pink-500",
  },
];

export const diseases = [
  { name: "Diabetes" },
  { name: "Cancer" },
  { name: "Heart Disease" },
  { name: "Stroke" },
  { name: "Hypertension" },
  { name: "Asthma" },
  { name: "COPD" },
  { name: "Alzheimer Disease" },
  { name: "Parkinson Disease" },
  { name: "Arthritis" },
  { name: "Osteoporosis" },
  { name: "Kidney Disease" },
  { name: "Liver Disease" },
  { name: "HIV/AIDS" },
  { name: "Tuberculosis" },
  { name: "Pneumonia" },
  { name: "COVID-19" },
  { name: "Influenza" },
  { name: "Bronchitis" },
  { name: "Chronic Fatigue Syndrome" },
  { name: "Celiac Disease" },
  { name: "Crohn Disease" },
  { name: "Ulcerative Colitis" },
  { name: "Irritable Bowel Syndrome (IBS)" },
  { name: "Diverticulitis" },
  { name: "Lupus" },
  { name: "Multiple Sclerosis" },
  { name: "Epilepsy" },
  { name: "Migraine" },
  { name: "Depression" },
  { name: "Anxiety" },
  { name: "Schizophrenia" },
  { name: "Bipolar Disorder" },
  { name: "Obsessive-Compulsive Disorder (OCD)" },
  { name: "Autism Spectrum Disorder" },
  { name: "Attention Deficit Hyperactivity Disorder (ADHD)" },
  { name: "Down Syndrome" },
  { name: "Sickle Cell Anemia" },
  { name: "Hemophilia" },
  { name: "Thalassemia" },
  { name: "Leukemia" },
  { name: "Lymphoma" },
  { name: "Melanoma" },
  { name: "Psoriasis" },
  { name: "Eczema" },
  { name: "Anorexia Nervosa" },
  { name: "Bulimia Nervosa" },
  { name: "Obesity" },
  { name: "Gout" },
  { name: "Hepatitis" },
  { name: "Polio" },
];
