//
//
// seed data for testing
const data = {
  users: [
    {
      name: "Ryan Rahman",
      email: "afnanfrince@gmail.com",
      password: "Test71@",
      phone: "07364823",
      address: "Dhaka, bangladesh",
      image: "null-image",
      isAdmin: true,
    },
    {
      name: "Ryan Rahman",
      email: "ryan@gmail.com",
      password: "Test71@",
      phone: "07364823",
      address: "Dhaka, bangladesh",
      image: "null-image",
      isAdmin: true,
    },
    {
      name: "Ryan",
      email: "test1@gmail.com",
      password: "Test71@",
      phone: "07364823",
      address: "Dhaka, bangladesh",
      image: "null-image",
    },
    {
      name: "Rumpa Rahman",
      email: "rumpa@gmail.com",
      password: "Test71@",
      phone: "06138343",
      address: "Dhaka, bangladesh",
      image: "null-image",
    },
  ],
  // diseases ---***
  diseases: [
    { name: "Diabetes" },
    { name: "Cancer" },
    { name: "Heart Disease" },
    { name: "Stroke" },
    { name: "Hypertension" },
    { name: "Asthma" },
    { name: "COPD" },
    { name: "Alzheimer Disease" },
    { name: "Parkinson Disease" },
    { name: "Arthritis" },
    { name: "Osteoporosis" },
    { name: "Kidney Disease" },
    { name: "Liver Disease" },
    { name: "HIV/AIDS" },
    { name: "Tuberculosis" },
    { name: "Pneumonia" },
    { name: "COVID-19" },
    { name: "Influenza" },
    { name: "Bronchitis" },
    { name: "Chronic Fatigue Syndrome" },
    { name: "Celiac Disease" },
    { name: "Crohn Disease" },
    { name: "Ulcerative Colitis" },
    { name: "Irritable Bowel Syndrome (IBS)" },
    { name: "Diverticulitis" },
    { name: "Lupus" },
    { name: "Multiple Sclerosis" },
    { name: "Epilepsy" },
    { name: "Migraine" },
    { name: "Depression" },
    { name: "Anxiety" },
    { name: "Schizophrenia" },
    { name: "Bipolar Disorder" },
    { name: "Obsessive-Compulsive Disorder (OCD)" },
    { name: "Autism Spectrum Disorder" },
    { name: "Attention Deficit Hyperactivity Disorder (ADHD)" },
    { name: "Down Syndrome" },
    { name: "Sickle Cell Anemia" },
    { name: "Hemophilia" },
    { name: "Thalassemia" },
    { name: "Leukemia" },
    { name: "Lymphoma" },
    { name: "Melanoma" },
    { name: "Psoriasis" },
    { name: "Eczema" },
    { name: "Anorexia Nervosa" },
    { name: "Bulimia Nervosa" },
    { name: "Obesity" },
    { name: "Gout" },
    { name: "Hepatitis" },
    { name: "Polio" },
  ],
};

module.exports = data;
